services:
  web:
    build: ./app
    ports:
      - "6969:5000"
    volumes:
      # Mount a folder for our persistent data (DB, settings)
      - ./data:/app/data
      # Mount the user's media library as read-only for browsing
      - /path/to/your/audiobooks:/media/audiobooks:ro
    restart: unless-stopped