services:
  web:
    build: ./app
    ports:
      - "6969:5000" # Changed: Access from your browser on port 6969
    volumes:
      # Mount a single folder to persist the DB, settings, and temp files
      - ./data:/app/data
    restart: unless-stopped