services:
  web:
    build: ./app
    ports:
      - "6969:5000"
    volumes:
      # We ONLY need to persist the app's internal data (DB, settings, and temp uploads).
      # No media library mount is needed.
      - ./data:/app/data
    restart: unless-stopped