version: '3.8'

services:
  web:
    build: ./app
    ports:
      - "5001:5000"
    volumes:
      - ./db:/usr/src/app/db
      - C:\path\to\your\audiobooks:/mnt/audiobooks:ro
    environment:
      - YOTO_EMAIL=your_email@example.com
      - YOTO_PASSWORD=your_yoto_password
      - MEDIA_FOLDER_PATH=/mnt/audiobooks
    restart: unless-stopped
